export const siteConfig = {
  name: 'Kiera Gordon Digital',
  strapline: 'Websites for independent beauty businesses.',
  description:
    'Graphic, booking-ready websites for independent beauty businesses.',
  email: 'hello@kieragordondigital.co.uk',
  phone: '',
  founderName: 'Kiera Gordon',
  launchPrice: '£149',
  offerLabel: 'Introductory launch price',
  offerNote:
    'Currently £149 while Kiera Gordon Digital builds its first client portfolio.',
  freeConceptPrice: '£0',
  ownershipLabel: '100%',
  pagesIncluded: 'Up to 5 core pages',
  turnaround: '7-10 working days after all required content has been received',
  turnaroundShort: '7-10 working days',
  revisions: 2,
  bugSupport: 'Short technical bug-fix period after launch',
  conceptCta: 'Get your free concept',
  conceptFormCta: 'Send my business',
  secondaryCta: 'View our work',
  microcopy: 'Free homepage concept · No payment details · No obligation',
  bookingPlatforms: ['Fresha', 'Treatwell', 'Booksy'],
  legalNote:
    'Starter legal pages are provided for practical launch preparation and are not legal advice.',
  socialLinks: [] as Array<{ label: string; href: string }>,
  atelierUnionLiveUrl: 'https://atelier-union.onrender.com/',
  formEndpoint: '',
  footerStatement: 'Websites for independent beauty businesses.',
};
